# Generated by Django 4.2 on 2023-04-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('airport', models.CharField(max_length=50)),
                ('extras', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
