# Generated by Django 4.2 on 2023-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='aviatickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('fly_from', models.CharField(max_length=50)),
                ('fly_for', models.CharField(max_length=50)),
                ('flies_time', models.TimeField()),
                ('fly_start_time', models.TimeField()),
            ],
        ),
    ]
