# Generated by Django 4.2 on 2023-04-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aviatickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviatickets',
            name='fly_start_time',
            field=models.DateTimeField(),
        ),
    ]
