# Generated by Django 4.2 on 2023-05-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aviatickets_number_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviatickets',
            old_name='fly_for',
            new_name='fly_to',
        ),
    ]
