# Generated by Django 4.2 on 2023-05-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_fly_for_aviatickets_fly_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviatickets',
            old_name='fly_start_time',
            new_name='date',
        ),
    ]
