# Generated by Django 4.2 on 2023-05-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_fly_start_time_aviatickets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviatickets',
            name='date',
            field=models.DateField(),
        ),
    ]
